# Generated by Django 4.1.7 on 2023-05-04 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='type',
            new_name='type_opp',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opportunitie', to='opportunity.stage'),
        ),
    ]
